"""add computed spread table

Revision ID: af513ee4d2a7
Revises: 1313e71b56c4
Create Date: 2025-09-29 00:51:11.419687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af513ee4d2a7'
down_revision: Union[str, Sequence[str], None] = '1313e71b56c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computed_spread_max',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('high_exchange_id', sa.Integer(), nullable=False),
    sa.Column('low_exchange_id', sa.Integer(), nullable=False),
    sa.Column('spread_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['high_exchange_id'], ['supported_exchanges_by_crypto.id'], ),
    sa.ForeignKeyConstraint(['id'], ['crypto_pairs_names.id'], ),
    sa.ForeignKeyConstraint(['low_exchange_id'], ['supported_exchanges_by_crypto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computed_spread_max')
    # ### end Alembic commands ###
