"""add crypto_id to batch status table

Revision ID: 1313e71b56c4
Revises: 4ad6985e20a7
Create Date: 2025-09-25 18:41:01.740103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1313e71b56c4'
down_revision: Union[str, Sequence[str], None] = '4ad6985e20a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_status', sa.Column('crypto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'batch_status', 'crypto_pairs_names', ['crypto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batch_status', type_='foreignkey')
    op.drop_column('batch_status', 'crypto_id')
    # ### end Alembic commands ###
