"""add_unique_constraint

Revision ID: 4ad6985e20a7
Revises: 8139d232e7f1
Create Date: 2025-09-25 17:51:27.255609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad6985e20a7'
down_revision: Union[str, Sequence[str], None] = '8139d232e7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_id_to_exchange', 'supported_exchanges_by_crypto', ['crypto_id', 'supported_exchange'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_id_to_exchange', 'supported_exchanges_by_crypto', type_='unique')
    # ### end Alembic commands ###
