"""add_status_table

Revision ID: 8139d232e7f1
Revises: 34a70cb45479
Create Date: 2025-09-24 19:22:02.570728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8139d232e7f1'
down_revision: Union[str, Sequence[str], None] = '34a70cb45479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('saved_cache', sa.Boolean(), nullable=False),
    sa.Column('difference_found', sa.Boolean(), nullable=False),
    sa.Column('saved_db', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['supported_exchanges_by_crypto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_status')
    # ### end Alembic commands ###
