"""add_indexing_to_crypto_names

Revision ID: 34a70cb45479
Revises: 0a5539ee03e7
Create Date: 2025-09-20 12:21:10.101418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a70cb45479'
down_revision: Union[str, Sequence[str], None] = '0a5539ee03e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('crypto_pairs_names_crypto_name_key'), 'crypto_pairs_names', type_='unique')
    op.create_index(op.f('ix_crypto_pairs_names_crypto_name'), 'crypto_pairs_names', ['crypto_name'], unique=True)
    op.create_index(op.f('ix_supported_exchanges_by_crypto_supported_exchange'), 'supported_exchanges_by_crypto', ['supported_exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supported_exchanges_by_crypto_supported_exchange'), table_name='supported_exchanges_by_crypto')
    op.drop_index(op.f('ix_crypto_pairs_names_crypto_name'), table_name='crypto_pairs_names')
    op.create_unique_constraint(op.f('crypto_pairs_names_crypto_name_key'), 'crypto_pairs_names', ['crypto_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
