"""initial_schema

Revision ID: 0a5539ee03e7
Revises: 
Create Date: 2025-09-17 21:06:28.071774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5539ee03e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_pairs_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crypto_name')
    )
    op.create_table('supported_exchanges_by_crypto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('supported_exchange', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['crypto_pairs_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supported_exchanges_by_crypto')
    op.drop_table('crypto_pairs_names')
    # ### end Alembic commands ###
