services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - /backend/__pycache__
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
