services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - /src/__pycache__
      - /src/.pytest_cache
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - USE_ALEMBIC_LOCAL=false
      - REDIS_LOCAL=false
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      # Enable polling for file changes (important for Docker)
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: postgres
    # aren't necessary, can be skipped
    restart: always
    shm_size: 128mb
    environment:
      # only the password is mandatory
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
