services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - /src/__pycache__
      - /src/.pytest_cache
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      # Enable polling for file changes (important for Docker)
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
