FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get -y install libpq-dev gcc
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY src/ ./

CMD ["celery", "-A", "background.celery.celery_conf", "worker", "--loglevel", "INFO"]